### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by TanukiSoup** [ontrigger/ItemStatsMod#11]
The Spinel Tonic has no displayed stats and the tonic affliction item it generates shows some sort of error when hovered. Also the predatory mask doesn't list its flat 5% crit like the harvester's scythe does.
Edit: Also H3AD5T V2 doesn't mention the use of your intractable key to drop like the default desc. does.

**Comment by ontrigger** [comment]
ItemStats does not provide stats for equipment (for now), it also does not change the description. The rest is fixed
