### ISSUE TITLE
1.0 Update and Possibly Cross Mod Compatibility

### ISSUE THREAD

**Issue by imakunee** [ontrigger/ItemStatsMod#14]
Some information is incorrectly displayed in the tooltips of various items now. For example, Runald's Band still shows a stacking percent chance to activate in spite of the fact it is now a guaranteed proc at a specific damage point with a cooldown.

Also, seeing some kind of compatibility with the mod Classic Items from ThinkInvis would be fantastic though I expect it would require some effort on both creators' halves. One can dream though.

Thank you for your work on this mod! It is greatly helpful to just quickly reference the item you are holding for how it stacks when making decisions mid game rather than tabbing out and researching.

**Comment by RandomNerd1** [comment]
+1, this was the most useful mod, please release 1.0 update <3

**Comment by ontrigger** [comment]
1.0 items are already added, use the prerelease version to check them out
