### ISSUE TITLE
Add comparability for ClassicItems Mod

### ISSUE THREAD

**Issue by nickg11** [ontrigger/ItemStatsMod#16]
https://github.com/ThinkInvis/RoR2-ClassicItems

Would it be possible to add the scaling portion of the tooltip to the classic items mod? It currently shows the correct description for the item but it does not show how the amount of stacks scale. Or is this a change that would be on the end of ClassicItems considering half the mod already functions.

**Comment by nickg11** [comment]
Gonna try my hand at this and see if I can figure this out.

**Comment by ontrigger** [comment]
This is entirely on the end of ClassicItems. They have to use the API provided by itemstats to add the stat counters.

**Comment by nickg11** [comment]
I have brought it up with the creator classicItems and he said he would take a look.

**Comment by nickg11** [comment]
Is there an ETA on when the API will be added to itemstats on thunderstore? The dev of classicItems says that the API mentioned in the readme is not in the thunderstore version.

**Comment by ontrigger** [comment]
That's because 2.0 isnt released, but there is a prerelease build. Hovewer, I'd advise not to use the API for now as im planning to redo the stat calculation entirely
