### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by YoungGooby** [ontrigger/ItemStatsMod#2]
I'm getting this error. Is it bad?

https://i.imgur.com/y27P2TL.png

**Comment by tydude2641** [comment]
you have to reinstall r2api, but since the latest scorched acres update, r2api isnt updated for ror2. so you have to pull the latest "beta" dll of r2api off the ror2 modding discord, i would provide the link here but i dont know if that's okay. msg me on discord if you want: Tydude2641#5871
