### ISSUE TITLE
Why not show over 100% chances on certain items?

### ISSUE THREAD

**Issue by itsPoipoi** [ontrigger/ItemStatsMod#21]
Since Proc Coefficient is a pretty big thing, why not show >100% on certain items, like Tri-Tip Daggers, for example? I think it would be useful information.
Let's say we're shooting MUL-T's Nail Gun, with a PC of 0.6, we need 180% chance of proccing the daggers to proc them on every nail gun hit.
Same thing for Sticky Bombs, and all other items which currently display "Max Stacks" in their tooltips from the mod.
Also, I don't know if that's correct, but I believe 20 stacks of Stickies don't equate to a 100% proc chance, since the stacks scale exponentially.

**Comment by ontrigger** [comment]
Absolutely not. First of all, proc chance is a hidden mechanic. Nowhere does it say in any of the item descriptions that there is a magic variable that affects the chance of procing said item. 
Now I would have pondered adding it as a stat modifier if it was a fixed number based on the character, however, the proc chance is different based on the character's abilities, meaning that if I were to show it in the tooltip, it would only be accurate for one ability. 
As for showing > 100%, that's just dumb lol.

**Comment by itsPoipoi** [comment]
You should consider it, instead of just saying it's dumb. That's not very productive or mature.
Some items have hidden effects, but you still include them in the stats, like the hidden crit bonus of the two green crit items. Also, the devs explained proc coefficient is a thing in Dev Thoughts #1 I believe. So it doesn't matter that it doesn't say anything about PC in the item descriptions, PC is still there and taken into account.
I'm obviously not asking to show chances based on PC on the item stats, since PC is variable. I'm asking to show over 100% because "100%" isn't actually 100% for a lot of procs. Have you played this game?? "100%" with the nail gun is really only 60%, for example. If you allow stats to show over 100%, then it's up to the player to know the PC of the ability of his choice. Once again using the nail gun example, if you allow stats to show over 100%, one would know that nail gun will actually proc the item on every hit past the 166% threshold. Not showing >100% just means once one gets into late game and wants to optimize, your mod becomes obsolete on certain items, and the player has to do the math themselves to cap the item's proccing.
Actually give it some thought instead of just being stubborn. Or tell me why I'm wrong instead of just saying it's dumb.
