### ISSUE TITLE
Bugs noticed

### ISSUE THREAD

**Issue by Zurpx** [ontrigger/ItemStatsMod#3]
Tri-tip Dagger - Clover's effect doesn't show up on the tool tip when you hover over it. I think it does affect it, but not 100% sure.

Stun Grenade - 1 stack doesn't show as 5%, are you showing the actual value the engine uses? (If so, great)

Old Guillotine - I think this one stacks like the teddy bear, in a logarithmic fashion.

AtG Missile - The tool tip shows the chance going up with more than 1 stack. Only damage increases, chance is static.

Predatory Instincts - This items grants 5% crit chance for the first stack, like the Harvester's Scythe. Also, additional stacks increase potential attack speed by 20% per stack instead of 30%. So 30% at 1, 50% at 2, 70% at 3, etc..

Fire and Ice Rings - They have 8% separately, but if you have at least 1 of each, they both proc whenever the 1 of them does. I think the chance works out to if you had just 1 with a clover (not sure though). Be neat if the tool tip shows this functionality.

Rejuvenation Rack - I don't think these have a proc chance, they just guarantee increase healing.

Aegis - This caps at 5 (100% of your health). So I suppose you could just show it's at max, like with the crit glasses.

Halcyon Seed - Both the health and damage values aren't stacking properly on the tool tip. Should be 100% hp per stack, while damage is 100% for the first stack, then +50% each after.

Equipment / Spinal Tonic - Curious to know if you plan on showing more info for these items as well.

I think that's everything. I like your mod a lot, hope to see you keep it around for the future :D

**Comment by ontrigger** [comment]
I'll move this to a separate issue to resolve stuff not counted as a bug later

**Comment by ontrigger** [comment]
stun grenade shows the actual game value;
the seed shows health/damage values as the game calculates them (with the difficulty bonus). I will consider changing it to description-accurate values instead.
as for improvements - all of that should be in a separate issue
