### ISSUE TITLE
Anniversary Update Reminder

### ISSUE THREAD

**Issue by Hi-ImKyle** [ontrigger/ItemStatsMod#30]
RoR2 just got it's anniversary update! Along with some new items and changes to existing items I imagine this is a tad out of date now. :)

**Comment by ontrigger** [comment]
I am currently extremely busy and won't be able to work on the mod for the next 2 months, but you can always submit a pull request.

**Comment by Hi-ImKyle** [comment]
Sure thing, this was more of a "issue" to just make sure you haven't just abandoned it, I can try my best to make an update and create a PR for it, no promises! Don't stress yourself with this :)

**Comment by yawnston** [comment]
I looked into what seems to be the problem, and unfortunately there's more issues than just outdated or missing items. RoR2 made a breaking change in the items API and basically anything that relied on getting an `ItemIndex` is broken right now. Before, the `ItemIndex` enum had all the item values, but now the way to get indices is using `ItemCatalog`. Before we would do `ItemIndex.Mushroom`, now we have to do `ItemCatalog.FindItemIndex("Mushroom)`.

I'm generally a backend guy and I don't know much about Unity, but I'll try to submit a fix if I can.
