### ISSUE TITLE
Multiplayer UI Bugging Out

### ISSUE THREAD

**Issue by GalacticRuler** [ontrigger/ItemStatsMod#5]
When a player spectates with this installed on all clients; and host, people sometimes show as the wrong character and with a ton of !'s stacked to 20

**Comment by ontrigger** [comment]
uhh, could you show a screenshot of how exactly that looks?

**Comment by ontrigger** [comment]
also, I don't use the ! character anywhere I think, so it could be vanilla or some other mod

**Comment by GalacticRuler** [comment]
it's Item Stats Mod; see here:
![ss (2019-09-23 at 10 41 16)](https://user-images.githubusercontent.com/1534478/65477133-5dde1c80-de53-11e9-8e33-488c6f89a674.png)
![Uploading ss (2019-09-23 at 10.41.50).png…]()

**Comment by GalacticRuler** [comment]
This was in multiplayer with 2 people. clicking continue does nothing for me, the host.
I was killed by a stone titan as Merc, not a turret as commando

**Comment by GalacticRuler** [comment]
It's got something to do with Strides of Heresy. only happens when someone has that item

**Comment by ontrigger** [comment]
yes, I know, just can't fix it right now

**Comment by ontrigger** [comment]
Fixed in the latest set of commits
