### ISSUE TITLE
Out of date for Hidden Realms Update

### ISSUE THREAD

**Issue by GalacticRuler** [ontrigger/ItemStatsMod#6]
Any chance we could see a patch soonish?

**Comment by ontrigger** [comment]
I'm a bit busy right now, so I'd say you're gonna have to wait a week or maybe less for that

**Comment by Macapple96** [comment]
For instance, the mod works perfectly as usual and doesn't crash or anything. It's just missing the new items in case you were wondering @GalacticRuler
