### ISSUE TITLE
Stats dont seem to add up

### ISSUE THREAD

**Issue by Deathpyre** [ontrigger/ItemStatsMod#7]
Hey there! First, I love that you created this mod and are still updating it, so thank you. I haven't used it long but I immediately noticed some of the numbers don't seem to add up. I'm guessing maybe the values updated in the last patch for some items and your algorithm numbers might need updated. Examples:
Ttougher times says it gives +15% per stack, but the total is 13% when you get the item. 
Cautious slug is +4 hp/s out of combat, but the total says "300% health regen" (this may be on purpose and I just don't under stand some part?)

**Comment by ontrigger** [comment]
tougher times does not stack linearly, but the cautious slug bug will be fixed in the next update

**Comment by Deathpyre** [comment]
Alright, it looks like you're right looking it up. So strange it works that way, thank you for replying.
